name: Deploy frontend application for todo
'on':
  push:
    branches:
      - todo
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3     
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: prepare the docker-compose-todo run
        run: |
              ls -l
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nefelibata0531/my-final-work-website:latest
      -
        name: copy docker-compose-todo.yml via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose-todo.yml"
          target: "/home/ecs-user/frontend"    
      -
        name:   docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ecs-user/frontend
            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose -f docker-compose-todo.yml down
            docker compose -f docker-compose-todo.yml pull
            docker compose -f docker-compose-todo.yml up -d
            rm -rf /home/ecs-user/frontend